### PR TITLE
Fix missing dependencies

### PR DESCRIPTION
**Pull request by 2maz**
Building with separate package prefixes exposed multiple include issues,
resulting from incomplete dependencies given. This commit fixes these issues.

### CODE REVIEW

**Comment by malter** [comment]
Many of the added dependencies in the app/CMakeList.txt are not required. We should only add the ones that are really directly used or where the app has to link to. The app dynamically ask the lib_manager for some libraries that are not required but are loaded by default if they exists. For instance the app can also run completely without graphical interface and thus should also build without the dependencies.

**Comment by 2maz** [comment]
Fine with me - the missing dependencies were to get it working for the Debian packaging and separate_prefixes enabled.
Since you know best what should be there, just update the PR accordingly by stripping the list down.

**Comment by 2maz** [comment]
There were still missing dependencies, so I updated mars_interfaces.pc file

```
In file included from /opt/rock/master-20.10/rock-master-20.10-simulation-mars-interfaces/include/mars/interfaces/sim/ControlCenter.h:39,
                 from /build/rock-master-20.10-simulation-mars-app-0.20201014/src/MARS.cpp:38:
/opt/rock/master-20.10/rock-master-20.10-simulation-mars-interfaces/include/mars/interfaces/sim/../Logging.hpp:17:10: fatal error: mars/data_broker/DataBrokerInterface.h: No such file or directory
 #include <mars/data_broker/DataBrokerInterface.h>
```

**Comment by 2maz** [comment]
@malter with the updated pc file, Debian package generation is working now

**Pull request merged**
