### PR TITLE
Throw a error is parsing of a obj files failes

### PR DESCRIPTION
**Pull request by goldhoorn**
This is related to: https://github.com/rock-simulation/mars/issues/44
and throw a correct error if something goes wrong

### CODE REVIEW

**Comment by goldhoorn** [comment]
Error still exists scene can be found [here](https://www.dropbox.com/s/q18bw7fwblrslak/pioneer3at.smurf?dl=0)

**Comment by malter** [comment]
Hey,

could you please check for:
  if(!completeNode.valid())

Then I will merge the request.

**Comment by goldhoorn** [comment]
@malter : updated

**Comment by malter** [comment]
completeNode is a osg::ref_ptr, so checking only for valid() is enough

**Comment by goldhoorn** [comment]
On 02.09.2015 11:52, malter wrote:
>
> completeNode is a osg::ref_ptr, so checking only for valid() is enough
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-simulation/mars/pull/47#issuecomment-137006496>.
>
But this is a pointer so the previous check does the same?!
http://trac.openscenegraph.org/documentation/OpenSceneGraphReferenceDocs/a00666.html#a45762261ee109e1d20d458afecff8e32

so why do you want to check against valid?

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by malter** [comment]
That's correct, but in mars_graphics I try to use always the valid() function. Then it's clear that it is a osg::ref_ptr and not a c pointer and it's consistent in the library.

**Comment by goldhoorn** [comment]
All updated

**Comment by malter** [comment]
now your commit message looks wrong? ;-)

**Comment by goldhoorn** [comment]
hmhmmhmhmmhmhmhmmhmhmhmh *updated*

**Pull request merged**
