### PR TITLE
Cleanup 1

### PR DESCRIPTION
**Pull request by goldhoorn**
This cleanup consists of three commits:
1. separate the logging to make the include easier
2. fix of some compiler warnings
3. move the tmp folder for linux based systems to /tmp

### CODE REVIEW

**Comment by goldhoorn** [comment]
@malter what do you think?

**Comment by malter** [comment]
I'm still not happy with this solution. We should stay backward compatible with deprecated warnings instead of forcing the users to adapt their plugins.
From my point of view, we could add the base_types dependency to the mars_interfaces and keep the macro definition there. So if ROCK is defined we could include the base/logging instead of defining the macros?

**Comment by goldhoorn** [comment]
What is about waiting for the next release cycle and breaking the 
backward compatibilty for the new version?.

Old oders could still stay then to the released (and tagged) version of 
mars.
I would like to go for this clear sepearation into a single header.

Best,
Matthias

On 12.01.2015 10:27, malter wrote:
>
> I'm still not happy with this solution. We should stay backward 
> compatible with deprecated warnings instead of forcing the users to 
> adapt their plugins.
> From my point of view, we could add the base_types dependency to the 
> mars_interfaces and keep the macro definition there. So if ROCK is 
> defined we could include the base/logging instead of defining the macros?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-simulation/mars/pull/15#issuecomment-69545022>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
*upated*

**Comment by malter** [comment]
The base-lib dependency can be added for windows, too.
And if you add the logging include to the ControlCenter.h nobody has to adapt their code now. In the next release cycle we can remove the include there?

**Pull request merged**
